language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install git+http://github.com/wyldebeast-wunderliebe/w20e.forms#egg=w20e.forms
  - pip install -r requirements.txt --use-mirrors
  - python setup.py develop
# command to run tests
script: py.test --cov w20e.hitman
