language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install converage
  - pip install git+http://github.com/wyldebeast-wunderliebe/w20e.forms#egg=w20e.forms
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script: nosetests
